# Generated by Django 4.2.4 on 2023-08-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilkTea_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
